apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: petclinic-src-to-run
  namespace: default
spec:
  runLatest:
    configuration:
      build:
        serviceAccountName: build-bot
        source:
          git:
            url: https://github.com/paulczar/spring-petclinic.git
            revision: docker-build-docs
        template:
          name: kaniko
          arguments:
          - name: IMAGE
            value: docker.io/paulczar/spring-petclinic:latest
      revisionTemplate:
        spec:
          container:
            image: docker.io/paulczar/spring-petclinic:latest
            imagePullPolicy: Always
